import os
import requests
from exo.utils.config import Config
from exo.utils.helpers import read_file, write_file


class SkillCreator:
    """Skill creator class"""
    
    def __init__(self):
        self.config = Config()
    
    def create(self, skill_dir):
        """Create standard skill format"""
        # Validate configuration
        self.config.validate()
        
        # Read SKILL.md file
        skill_file = os.path.join(skill_dir, 'SKILL.md')
        if not os.path.exists(skill_file):
            raise Exception(f"SKILL.md file not found: {skill_file}")
        
        skill_content = read_file(skill_file)
        
        # Optimize skill content using OpenRouter API
        optimized_content = self._optimize_with_openrouter(skill_content)
        
        # Write optimized content
        write_file(skill_file, optimized_content)
        
        # Generate file structure for skill-creator
        self._generate_skill_structure(skill_dir)
        
        return skill_dir
    
    def _optimize_with_openrouter(self, content):
        """Optimize skill content using OpenRouter API"""
        headers = {
            'Authorization': f'Bearer {self.config.OPENROUTER_API_KEY}',
            'Content-Type': 'application/json'
        }
        
        data = {
            "model": "anthropic/claude-3-opus-20240229",
            "messages": [
                {
                    "role": "system",
                    "content": "You are an AI Agent skill optimization expert, responsible for converting raw content into standard skill format, ensuring the content is clear, structured, and suitable for AI Agent understanding and use."
                },
                {
                    "role": "user",
                    "content": f"Please optimize the following skill content to conform to standard skill format:\n\n{content}"
                }
            ],
            "temperature": 0.7
        }
        
        try:
            response = requests.post(
                self.config.OPENROUTER_API_URL,
                headers=headers,
                json=data,
                timeout=60
            )
            response.raise_for_status()
            result = response.json()
            return result.get('choices', [{}])[0].get('message', {}).get('content', content)
        except Exception as e:
            print(f"OpenRouter API call failed, using original content: {str(e)}")
            return content
    
    def _generate_skill_structure(self, skill_dir):
        """Generate file structure for skill-creator"""
        # Create necessary directories
        os.makedirs(os.path.join(skill_dir, 'scripts'), exist_ok=True)
        os.makedirs(os.path.join(skill_dir, 'assets'), exist_ok=True)
        os.makedirs(os.path.join(skill_dir, 'references'), exist_ok=True)
        
        # Create example script
        example_script = os.path.join(skill_dir, 'scripts', 'example.py')
        if not os.path.exists(example_script):
            script_content = """
"""
Skill example script"""

# Add skill execution logic here
print("Hello from EXO skill!")
"""
            write_file(example_script, script_content.strip())
        
        # Create README.md file
        readme_file = os.path.join(skill_dir, 'README.md')
        if not os.path.exists(readme_file):
            readme_content = """
# Skill README

This is a skill generated by EXO.

## Usage

Use this skill to access information from the source URL.
"""
            write_file(readme_file, readme_content.strip())
